version: '3.2'
services:
  dev:
    environment:
      spring_profiles_active: dev
    build: Docker/dev
    ports:
      - "8050:9090"
    volumes:
      - "./test-tmp/backend/config:/config"

  weather-mock:
    image: rodolpheche/wiremock
    ports:
      - 3000:8080
